name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build /home/runner/work/DockerIL/DockerIL/Nextcloud/ --file Dockerfile --tag my-image-name:$(date +%s)
